# Generated by Django 2.2.1 on 2019-05-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
