# Generated by Django 2.2.1 on 2019-05-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='poster',
            field=models.CharField(default='poster', max_length=999),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='companyName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='FlightCompanies',
        ),
        migrations.DeleteModel(
            name='HotelLocation',
        ),
    ]
