# Generated by Django 2.2.1 on 2019-05-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190513_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='stars',
        ),
    ]
