# Generated by Django 2.2.1 on 2019-05-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotels',
            field=models.IntegerField(default=3),
        ),
    ]
