<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-05-08 16:28
=======
# Generated by Django 2.2.1 on 2019-05-08 12:47
>>>>>>> 5d5623dd5a8ec9205468a9d50fae7414e48cbd55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190508_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
