# Generated by Django 2.2.1 on 2019-05-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190513_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotels',
            new_name='stars',
        ),
    ]
